application: ENTER_APPID_HERE
version: 1
runtime: python27
threadsafe: no
api_version: 1

inbound_services:
- warmup

libraries:
- name: PIL
  version: 1.1.7
- name: pycrypto
  version: 2.3
- name: webapp2
  version: latest

builtins:
- deferred: on


handlers:

# App Hosting Dev Console Admin, Warm Up handler, etc.

- url: /ahadmin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  secure: always
  login: admin

- url: /_ah/warmup
  script: cauliflowervest.server.main.app
  secure: always
  login: admin

# Crons.

- url: /cron/group_sync
  script: cauliflowervest.server.cron.group_sync.app
  secure: always
  login: admin

# Static Files

- url: /static
  static_dir: cauliflowervest/server/static
  secure: always
  login: required

# Regular URL handlers.

- url: /(bitlocker|duplicity|filevault|luks|provisioning|xsrf-token)/.*
  script: cauliflowervest.server.main.app
  secure: always
  login: required


- url: /.*
  script: cauliflowervest.server.main.app
  secure: always
  login: required
