language: node_js
python:
    - "2.7"
node_js:
    - "7"
before_script:
    - if [[ $(uname) == 'Linux' ]]; then sudo apt-get update; fi
    - if [[ $(uname) == 'Linux' ]]; then sudo apt-get install -y python-virtualenv python-tk; fi
    - npm install -g bower
script: make server_config
sudo: required
dist: trusty
os:
  - linux
  - osx

