language: c
before_script:
    - brew update
    - brew install bazel
    - sudo easy_install pip
    - sudo pip install pycrypto pillow
script: bazel test cauliflowervest:all_smoke_tests
sudo: required
osx_image: xcode8.3
os:
  - osx

